CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(64) NOT NULL UNIQUE CHECK (name <> ''),
    email   VARCHAR(64) NOT NULL UNIQUE CHECK (email <> '')
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL UNIQUE CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)                               NOT NULL CHECK (title <> ''),
    annotation         VARCHAR(2000)                              NOT NULL CHECK (annotation <> ''),
    category_id        BIGINT REFERENCES categories (category_id) NOT NULL,
    description        VARCHAR(7000) CHECK (description <> ''),
    created            TIMESTAMP WITHOUT TIME ZONE                NOT NULL,
    published          TIMESTAMP WITHOUT TIME ZONE,
    event_date         TIMESTAMP WITHOUT TIME ZONE                NOT NULL,
    lat                FLOAT                                      NOT NULL,
    lon                FLOAT                                      NOT NULL,
    paid               BOOLEAN                                    NOT NULL,
    initiator_id       BIGINT REFERENCES users (user_id)          NOT NULL,
    participant_limit  BIGINT                                     NOT NULL,
    request_moderation BOOLEAN                                    NOT NULL,
    state              VARCHAR                                    NOT NULL CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'))

);

CREATE TABLE IF NOT EXISTS participation_requests
(
    participation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created                  TIMESTAMP WITHOUT TIME ZONE         NOT NULL,
    requester_id             BIGINT REFERENCES users (user_id)   NOT NULL,
    event_id                 BIGINT REFERENCES events (event_id) NOT NULL,
    status                   VARCHAR                             NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(120) NOT NULL CHECK (title <> ''),
    pinned         BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS event_compilations
(
    compilation_id BIGINT REFERENCES compilations (compilation_id) NOT NULL,
    event_id       BIGINT REFERENCES events (event_id)             NOT NULL,
    UNIQUE (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(2000)               NOT NULL CHECK (text <> ''),
    event_id   BIGINT REFERENCES events (event_id),
    author_id  BIGINT REFERENCES users (user_id),
    created    TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
