CREATE TABLE IF NOT EXISTS apps
(
    app_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(64) UNIQUE NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS hits
(
    hit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id    BIGINT REFERENCES apps (app_id) NOT NUll,
    uri       VARCHAR(64)                     NOT NULL CHECK (uri <> ''),
    ip        VARCHAR(15)                     NOT NULL CHECK (ip <> ''),
    timestamp TIMESTAMP WITHOUT TIME ZONE     NOT NULL
);
